name: Build and Run

on: [push, pull_request]

jobs:
  sender_job:
    build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
      - name: Run and collect coverage
        run: |
          coverage run --branch sender/stream_line_sender.test.py
          coverage html
          coverage report
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 21
      - name: Build sender
        run: |
          pyinstaller --onefile sender/stream_line_sender.executable.py
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: pyinstaller
          path: dist/stream_line_sender.executable
      - name: Run build
        run: |
          dist/stream_line_sender.executable

  receiver_job:
    build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -g -o receiver ./receiver/*.c* -D UTEST

    - name: run
      run: ./receiver/receiver

    - name: collect coverage
      run: gcovr --exclude=".*test\.*" -r . --html --html-details -o ./receiver/coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21